### PR TITLE
Feature/fix pipeline

### PR DESCRIPTION
**Pull request by Tugark**
As discussed:

* Moved all files to the root folder (no need for `app`)
* Adjusted the deployment configuration (note: the todo will be removed once this is merged; it was necessary to add my feature branch to avoid having to clutter the main branch)
* I also had to fix the `threejs` dependency due to some peer issues; I think we'd have to work a bit there as well :D

Currently, this is the version that is deployed at https://opensource-construction.github.io/infraweb/ (to check whether it is this version, see the tab title which I also changed).

@Curiosit Can you quickly check whether it works and all the necessary changes you made are in? If so, feel free to merge it.

I'd also suggest that we turn  on branch protection afterwards, so all changes need to be done in feature branches and PRs, and then we can also add pipelines to check for buildability on PRs to ensure we always have a working version.

### CODE REVIEW

**Comment by Tugark** [comment]
@Curiosit Also note: Once this is merged, I will also remove the todo as well as update the `README` and remove the manual deployment step dependencies.

**Comment by Curiosit** [comment]
@Tugark thanks! I have just checked - it seems to be running fine!
+1 to the branch protection and only commiting to feature branches

**Comment by Tugark** [comment]
@Curiosit Branch protections are enabled and PRs require at least one approval now.

I will also add an action tomorrow (or when I get to that this week) that will run the builds on a PR opening, so we can enforce this as well.

...and then we could discuss about enforcing more things, like clean code, linting etc.; but then we'd have to have a quick meeting about where we are heading with it? :)

**Comment by Curiosit** [comment]
Great! Let's talk when you have time. I think it would be cool to finalize on the initial idea of automated DWG/SVG/PDF/something else export

**Pull request merged**
